[package]
name = "logprob"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.17"

[dev-dependencies]
divan = "0.1.8"
anyhow = "1.0"
approx = "0.5.1"
rand = "0.8.5"
rand_chacha = "0.3.1"

[[bench]]
name = "allocating_log_sum_exp"
harness = false
